---
title: "Final Dashboard"
output:   
  
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(leaflet)
library(mapview)
library(tmap)
library(sf)
library(cluster)

library(ggplot2)
myWeb= "https://github.com/vshaw2/543-Visual-Analytics/raw/main/"
```
```{r}
kc_demographics= readRDS(file=url(paste0(myWeb, "kc_demographics.rds")))
roads=read.csv(paste0(myWeb,"Geographic%20Data%20Roads%20Projects.csv"))
roadsproj=read.csv(paste0(myWeb,"Projects%20-%20January%2024%2C%202022.csv"))
```

[comment]: # (code for plots in this column)

```{r, bivariate}
library(tidyverse)
categoryToSelect=c("Drainage","Roadway","Roadside","Traffic Control","Bridges & Structures")
torisSubSet=roadsproj[roadsproj$Portfolio.Category%in%categoryToSelect,]

toRecode=c("Roadway","Roadside","Traffic Control")
ifelse(torisSubSet$Portfolio.Category%in%toRecode, 
       "Road and Traffic",
       torisSubSet$Portfolio.Category)

torisSubSet$Portfolio.Category= ifelse(torisSubSet$Portfolio.Category%in%toRecode,
                                       "Road and Traffic",
                                       torisSubSet$Portfolio.Category)
varsToSelect=c("Portfolio.Category","Gate.1","Gate.2","Gate.3",
               "Gate.1..Performance.Reference.","Gate.2..Performance.Reference.","Gate.3..Performance.Reference.","Number", "Name")
torisSubSet=torisSubSet[,varsToSelect]

DateColumns=c("Gate.1","Gate.2","Gate.3",
               "Gate.1..Performance.Reference.","Gate.2..Performance.Reference.","Gate.3..Performance.Reference.")

torisSubSet[,DateColumns]=lapply(torisSubSet[,DateColumns],as.Date,format='%m/%d/%Y')

torisSubSet

torisCompleteDates=torisSubSet[complete.cases(torisSubSet),]
torisCompleteDates

torisCompleteDates[,8:10]=0
torisCompleteDates[,8:10]=torisCompleteDates[,2:4]-torisCompleteDates[,5:7]
names(torisCompleteDates)[8:10]=c("Diff1","Diff2","Diff3")
torisCompleteDates[,8:10]=lapply(torisCompleteDates[,8:10],as.numeric)
torisCompleteDates[,8:10]

aggregate(data=torisCompleteDates,
          cbind(Diff1,Diff2,Diff3)~Portfolio.Category,
          FUN=mean)
```
```{r,map}
set.seed(23994)
vars <- c('med_income', 'p_e_less','percent_poc')
distances <- cluster::daisy(kc_demographics[,vars])
res.pam <- cluster::pam(x=distances,
                        k = 5,
                        cluster.only = F)
kc_demographics$cluster <- as.factor(res.pam$clustering)

kc_demographics$cluster <- factor(kc_demographics$cluster,
                                  levels=c(1,5,3,4,2),
                                  labels=c("low income diverse",
                                           "low income middle diverse",
                                           "middle income middle diverse", 
                                           "high income low diversity", 
                                           "middle income low diversity"),
                                  ordered=T)

```

Column {data-width=600}
-----------------------------------------------------------------------

###Plot 1
```{r}
LegLabel = 'ESJ Score by Census Tract' 

kc_demographics_SF=kc_demographics%>%st_sf()
ggplot()  + geom_sf(data=kc_demographics_SF, aes(fill=cluster))

roadssub=roads[complete.cases(roads$Latitude),]

roadsloc = st_as_sf(roadssub, coords = c("Longitude","Latitude"), 
                    crs = st_crs (kc_demographics_SF))
ggplot()  + geom_sf(data=roadsloc)

ggplot()  + 
    geom_sf(data=kc_demographics_SF, 
                    aes(fill=cluster), 
                    alpha=0.5) +  
    geom_sf(data=roadsloc, color='red') 
titleText = 'Roads Capital Projects Map with ESJ Score'
LegLabel = 'ESJ Score by Census Tract' 

ggplot()  + 
    geom_sf(data=kc_demographics_SF, 
                    aes(fill=cluster), 
                    alpha=0.5) +  
    geom_sf(data=roadsloc, color='red') + labs(title = titleText, caption = "King County") + theme(plot.title = element_text(hjust = 0.5)) + guides(fill=guide_legend(title="ESJ Score by Census Tract"))
```
Column {data-width=400}
-----------------------------------------------------------------------

###Plot 2
```{r}
phasesDF=as.data.frame(table(roadsproj$ï..Phase))
phasesDF <- roadsproj %>% filter(!roadsproj$ï..Phase%in%c("OPERATIONS","LAND"))


names(phasesDF)=c("Phase", "Count")

phasesDF$Phase <- factor(phasesDF$Phase, levels = c('PLANNING',
                                          'PREDESIGN',
                                          'DESIGN',
                                          'IMPLEMENT',
                                          'CLOSEOUT',
                                          'HOLD',
                                          'NOT SET'))


base=ggplot(data=phasesDF, aes(x=Phase,y=Count))
base+geom_bar(stat = "identity")

base <- ggplot(data, aes(x = Phase,
                   y = Count,
                   label = Count)) +
  theme_classic()

lolliplot_All = base + 
  geom_segment(aes(y = 0, 
                   yend = Count, 
                   x = Phase, 
                   xend = Phase),
               color = "gray")  +
  
 geom_point(size = 4, color = "Blue") +
  geom_text(nudge_x=0.3,show.legend = FALSE) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits = c(0, max)) + 
  theme(axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.line.x = element_blank()) +
  labs(title = title_Text, caption = "King County Road Services Division") +
  xlab(X_axis_title)

lolliplot_All

```

###Plot 3 
```{r}
DFtoPlot=torisCompleteDates[,c("Portfolio.Category","Diff1","Diff2","Diff3")]
DFtoPlot

library(reshape2)
DFtoPlot=melt(DFtoPlot,id.vars = 'Portfolio.Category')
DFtoPlot


base=ggplot(data=DFtoPlot) + theme_classic()
base + geom_boxplot(aes(x=Portfolio.Category,
                        y=value))

ggplot(data=DFtoPlot[DFtoPlot$Diff3!=2033,])

tapply(DFtoPlot$value,
       DFtoPlot$Portfolio.Category, summary)

base + geom_boxplot(aes(x=variable,
                        y=value))

base + geom_boxplot(aes(x=Portfolio.Category,
                        y=value)) + facet_wrap(variable~.) + coord_flip()

baseMEANs=ggplot(DFtoPlot, aes(x=Portfolio.Category,
                             y=value)) +
        theme_classic()
pointMEANS=baseMEANs + geom_point(stat="summary") + labs(title = "Average Gate Schedule Variance for Active Projects", caption = "King County Road Services Division") + xlab("Unit") + ylab("Average Schedule Variance(days) for Gate Dates") + theme(plot.title = element_text(hjust = 0.5))
pointMEANS

titleText = 'Schedule Variance of Roads Capital Projects'
sourceText = 'King County Road Services Division'

baseMEANs= ggplot(DFtoPlot[DFtoPlot$value!=2033,], aes(title=titleText, x=Portfolio.Category,
                      y=value, caption = sourceText)) +
        theme_classic()
jitterMEANs= baseMEANs + geom_jitter(colour="blue",
                             alpha=0.2)
jitterMEANs=jitterMEANs + geom_point(stat="summary") +
             geom_errorbar(stat="summary")
jitterMEANs + scale_y_continuous(breaks = c(100, 300, 500),labels = scales::comma) + labs(title = titleText, caption = sourceText) + xlab("Engineering Unit") + ylab("Milestone Schedule Variance (Days)") + theme(plot.title = element_text(hjust = 0.5))
```


